### ISSUE TITLE
Better commit message for site

### ISSUE THREAD

**Issue by LeeNX** [DrupalAssociationSA/DrupalAssociationSA.github.io#37]
Greetings ...  
  
I would really like to follow the site development, but with commit messages only containing the date and time is pretty meanless. @RiaanBurger , pleas try and add better commit messages.  #30 ?
  
Thanks

**Comment by RiaanBurger** [comment]
That's, unfortunately, just a function of the way static sites' complete
versions are pushed to the master branch with the Node github package. It
automatically deploys (pushes to master), so also automatically commits and
has to automatically add a commit message.

It's worthless following the commit messages on master branch anyway. The
work takes place on the Jekyll branch.

When you have a regular site to be hosted on GitHub, you use the gh_pages
branch to publish, but when you have an organisation one, you have to use
the master branch for publication.

On top of that, I've rushed through this and not merged all changes to
upstream for the Jekyll branch either, so the main repo may not be up to
date. We just have such short deadlines to get sponsors on board and do the
printing that every second saved helps.

**Comment by LeeNX** [comment]
That is UgLee!! I have disabled watching now, hope there is a better way worked out in future.

**Comment by RiaanBurger** [comment]
Perhaps see if you can track Jekyll branch only - those will make more sense.
